---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-role
  namespace: default
  labels:
    app: tools-rbac
# These rules allow us to make the service query, and write access to
# secrets. Delete is also granted so that we replace the secret on
# every boot, in case there have been service changes since the last
# web startup.
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["mqtt-pub-address"]
  verbs: ["update", "delete"]
---
# Standard role binding, connect these together.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-rolebinding
  namespace: default
  labels:
    app: tools-rbac
subjects:
- kind: ServiceAccount
  name: service-account-1
roleRef:
  kind: Role
  name: service-account-role
  apiGroup: ""
